name: Build MobyRewards XCFramework

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iOS Swift Package
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Xcode
        run: xcodebuild -version

      - name: Resolve package
        run: swift package resolve

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -scheme MobyRewards \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build/DerivedData \
            build

      - name: Build for iOS Device
        run: |
          xcodebuild \
            -scheme MobyRewards \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/DerivedData \
            build
